### ISSUE TITLE
[Reek] Support `--config` option

### ISSUE THREAD

**Issue by yykamei** [sider/runners#862] opened 2020-03-17 03:34 UTC
Currently, users can't specify an arbitrary Reek configuration file, but I think some of them want to place their Reek configuration file in another location.

https://github.com/troessner/reek#configuration-loading

**Comment by ybiquitous** [comment] 2020-03-17 03:54
Thanks for the report. But this is duplicate of #822

**Closed by ybiquitous** 2020-03-17 03:54 UTC
Labels: enhancement, language: ruby

**Comment by yykamei** [comment] 2020-03-17 04:21
Thank you for triaging.
